### PR TITLE
Header navbar on all pages

### PR DESCRIPTION
**Pull request by ErikOstien**

### CODE REVIEW

**Comment by dwang733** [comment]
Looks good to me, though there might be some conflicts between this PR and the other one, since I had made some changes in the other one (specifically with the clickable logo) that are deleted in this PR, so you might have to be careful about that.

**Comment by jlabowitz** [comment]
> Looks good to me, though there might be some conflicts between this PR and the other one, since I had made some changes in the other one (specifically with the clickable logo) that are deleted in this PR, so you might have to be careful about that.

@dwang733 I also noticed there are some conflicts. I think I will merge this one in first and then rebase the other branch with these changes.

**Comment by Juggernaut265** [comment]
Most of this seems okay, especially as there are 0 issues and no conflicts. Are you sure we need the "DS_Store" in ".gitignore"? What does this do?

**Comment by jlabowitz** [comment]
@Juggernaut265  We added DS_Store to .gitignore because Erik's computer kept trying to upload it. I thought we established it was a mac thing and it is definitely unnecessary to be in our repo. It shouldn't hurt anything.

**Pull request merged**
