### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by jlabowitz**
At this point, I really just updated the readme. If you have other things you would like to be clarified somewhere (either in the readme or in the code), let me know and I will provide more documentation there.

### CODE REVIEW

**Comment by nrleuenb** [comment]
An update fo you, since we don't have an image for the banner yet: how to update the banner image on the discovery page (keep in mind this hasn't been merged in yet). Go into `app/assets/images` and add the image file. Rename it to `discovery_image.jpeg`

**Comment by nrleuenb** [comment]
You might also want to include development instructions -- how to run tests, how to migrate the database, running bundle after every pull from master, etc.

**Comment by jlabowitz** [comment]
@nrleuenb I added how to run tests. I already mentioned how to put the database on heroku and other database practices are just rails standards. Also I'm not sure its necessary to write that you should run bundle after every pull from master. You only need to do that when the gemfile changes, and we already mention that someone pulling for the first time should run bundle install.

**Comment by jlabowitz** [comment]
Adnan, for the record, we talked about this PR over slack, so more than one person did review it.

**Pull request merged**
